sudo: required
services:
  - docker
language:
    - cpp

compiler:
    - gcc

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
      env: COMPILER=clang++-3.7

before_install:
  - sudo sudo apt-get install build-essential
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev

script:
    - cmake --version
    - pkg-config --list-all
    - gcc --version
    - ls
    - cat CMakeLists.txt
    - mkdir build
    - cd build
    - cmake ..
    - make
