sudo: required
services:
  - docker
language:
    - cpp

compiler:
    - gcc

script:
    - sudo apt-get install libgtest-dev
    - cmake --version
    - pkg-config --list-all
    - gcc --version
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-5.0
    - gcc --version
    - ls
    - cat CMakeLists.txt
    - mkdir build
    - cd build
    - cmake ..
    - make
