sudo: required
services:
  - docker
language:
    - cpp

compiler:
    - gcc

script:
    - sudo apt-get install libgtest-dev
    - cmake --version
    - pkg-config --list-all
    - gcc --version
    - ls
    - cat CMakeLists.txt
    - mkdir build
    - cd build
    - cmake ..
    - make
